### ISSUE TITLE
專案更新排序頁，可以直接把專案隱藏

### ISSUE THREAD

**Issue by marsz** [5fpro/jupiter#181]
更新排序頁 https://jupiter.5fpro.com/projects/edit

- 多一個 Archive 按鈕，點了就會直接把該專案移到歸檔區
- 新增一頁 https://jupiter.5fpro.com/projects/archived 可以列出已 archived 的專案
  - 可將 archived project 還原為 archived 前的狀態
  - /projects/edit 新增 link 連到 /projects/archived
- archived project:
  1. 不會顯示在 /projects
  2. 不會顯示在 /projects/edit
  3. /todos 下新增 TODO 時， project select bar 不會有該頁專案
  4. search form 的 select 不顯示 archived project => http://d.pr/i/Elr7

**Comment by telsaiori** [comment]
因為我想做這條試看看，可以請問一下之前兩個pr為什麼不能merge嗎？

**Comment by marsz** [comment]
@telsaiori 因為欄位開錯 model 了 QQ
專案排序是針對個人化的，所以 archive 也是同樣針對個人化的部份

**Comment by telsaiori** [comment]
所以其實不用是owner只要是專案成員誰都可以歸檔囉？（反正也只有自己看得到）
另外再請問一下，可以再新增table嗎？
因為現有model看不出來有哪邊適合新增相關欄位。

**Comment by marsz** [comment]
@telsaiori 
我後來有送了另外一個 PR https://github.com/5fpro/jupiter/pull/197
給你參考
其實有提供了 update project user 的 action 可以直接
另外我在過程中才想到 archive 時也要順便把該專案從排序清掉

ps: 之後有訊息要傳給我的話，可以 tag 我一下，我們有掛 direct message 通知 :p 感謝
